"""operation reason and note

Revision ID: 718948a9831a
Revises: 98112389f352
Create Date: 2026-09-26 05:59:52.024816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '718948a9831a'
down_revision: Union[str, Sequence[str], None] = '98112389f352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('reason', sa.String(length=16), nullable=True))
    op.add_column('operations', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    # Alembic autogenerate does not detect CHECK constraints; added by hand.
    op.create_check_constraint(
        "ck_operations_reason",
        "operations",
        "reason IS NULL OR reason IN ('count', 'damaged', 'lost', 'other')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_operations_reason", "operations", type_="check")
    op.drop_column('operations', 'note')
    op.drop_column('operations', 'reason')
    # ### end Alembic commands ###
