"""unique short_code for virtual locations

Revision ID: 98112389f352
Revises: faf76b45892a
Create Date: 2026-09-26 05:16:46.234134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98112389f352'
down_revision: Union[str, Sequence[str], None] = 'faf76b45892a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_locations_virtual_short_code', 'locations', ['short_code'], unique=True, postgresql_where=sa.text('warehouse_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_locations_virtual_short_code', table_name='locations', postgresql_where=sa.text('warehouse_id IS NULL'))
    # ### end Alembic commands ###
