"""initial schema

Revision ID: faf76b45892a
Revises: 
Create Date: 2026-09-26 04:59:02.965419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf76b45892a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login_id')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_code', sa.String(length=12), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_code', sa.String(length=24), nullable=False),
    sa.Column('type', sa.Enum('internal', 'vendor', 'customer', 'adjustment', name='location_type'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'short_code', name='uq_locations_warehouse_short_code')
    )
    op.create_index('ix_locations_type', 'locations', ['type'], unique=False)
    op.create_index('ix_locations_warehouse_id', 'locations', ['warehouse_id'], unique=False)
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_resets_user_id'), 'password_resets', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('uom', sa.String(length=24), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('min_qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False)
    op.create_table('sequences',
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('op_type', sa.String(length=16), nullable=False),
    sa.Column('next_value', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("op_type IN ('receipt', 'delivery', 'internal', 'adjustment')", name='ck_sequences_op_type'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('warehouse_id', 'op_type')
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('receipt', 'delivery', 'internal', 'adjustment', name='operation_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'waiting', 'ready', 'done', 'canceled', name='operation_status'), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('delivery_address', sa.String(length=500), nullable=True),
    sa.Column('source_location_id', sa.Integer(), nullable=False),
    sa.Column('dest_location_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('responsible_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dest_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index('ix_operations_dest_location_id', 'operations', ['dest_location_id'], unique=False)
    op.create_index('ix_operations_scheduled_date', 'operations', ['scheduled_date'], unique=False)
    op.create_index('ix_operations_source_location_id', 'operations', ['source_location_id'], unique=False)
    op.create_index('ix_operations_status', 'operations', ['status'], unique=False)
    op.create_index('ix_operations_type', 'operations', ['type'], unique=False)
    op.create_table('stock_quants',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('reserved', sa.Numeric(precision=12, scale=3), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_stock_quants_quantity_non_negative'),
    sa.CheckConstraint('reserved >= 0', name='ck_stock_quants_reserved_non_negative'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'location_id')
    )
    op.create_index('ix_stock_quants_location_id', 'stock_quants', ['location_id'], unique=False)
    op.create_table('operation_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.CheckConstraint('qty > 0', name='ck_operation_lines_qty_positive'),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_operation_lines_operation_id', 'operation_lines', ['operation_id'], unique=False)
    op.create_index('ix_operation_lines_product_id', 'operation_lines', ['product_id'], unique=False)
    op.create_table('stock_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=False),
    sa.Column('to_location_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('qty > 0', name='ck_stock_moves_qty_positive'),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_moves_created_at', 'stock_moves', ['created_at'], unique=False)
    op.create_index('ix_stock_moves_from_location_id', 'stock_moves', ['from_location_id'], unique=False)
    op.create_index('ix_stock_moves_operation_id', 'stock_moves', ['operation_id'], unique=False)
    op.create_index('ix_stock_moves_product_id', 'stock_moves', ['product_id'], unique=False)
    op.create_index('ix_stock_moves_to_location_id', 'stock_moves', ['to_location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_moves_to_location_id', table_name='stock_moves')
    op.drop_index('ix_stock_moves_product_id', table_name='stock_moves')
    op.drop_index('ix_stock_moves_operation_id', table_name='stock_moves')
    op.drop_index('ix_stock_moves_from_location_id', table_name='stock_moves')
    op.drop_index('ix_stock_moves_created_at', table_name='stock_moves')
    op.drop_table('stock_moves')
    op.drop_index('ix_operation_lines_product_id', table_name='operation_lines')
    op.drop_index('ix_operation_lines_operation_id', table_name='operation_lines')
    op.drop_table('operation_lines')
    op.drop_index('ix_stock_quants_location_id', table_name='stock_quants')
    op.drop_table('stock_quants')
    op.drop_index('ix_operations_type', table_name='operations')
    op.drop_index('ix_operations_status', table_name='operations')
    op.drop_index('ix_operations_source_location_id', table_name='operations')
    op.drop_index('ix_operations_scheduled_date', table_name='operations')
    op.drop_index('ix_operations_dest_location_id', table_name='operations')
    op.drop_table('operations')
    op.drop_table('sequences')
    op.drop_index('ix_products_category_id', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_password_resets_user_id'), table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index('ix_locations_warehouse_id', table_name='locations')
    op.drop_index('ix_locations_type', table_name='locations')
    op.drop_table('locations')
    op.drop_table('warehouses')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
    # Autogenerate creates the PG enum types implicitly with the tables but never
    # drops them, which breaks downgrade -> upgrade. Drop them explicitly.
    bind = op.get_bind()
    for enum_name in ('operation_status', 'operation_type', 'location_type'):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
